[package]
name = "solana-cpi-invoke"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=1.18.5"
borsh = "0.10.3"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []